volumes:
  todo_local_postgres_data: {}
  todo_local_postgres_data_backups: {}
  todo_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: todo_local_django
    container_name: todo_local_django
    tty: true
    depends_on:
      - postgres
      - redis
      - mailpit
      - keycloak
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    expose:
      - 8000
    command: /start
    network_mode: host

  postgres:
    image: postgres:15.10
    container_name: todo_local_postgres
    tty: true
    expose:
      - 5432
    stop_grace_period: "3s"
    volumes:
      - todo_local_postgres_data:/var/lib/postgresql/data
      - ./compose/local/postgres:/backups
    env_file:
      - ./.envs/.local/.postgres
    network_mode: host

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: todo_local_mailpit
    expose:
      - 8025
    network_mode: host

  redis:
    image: docker.io/redis:6
    container_name: todo_local_redis
    volumes:
      - todo_local_redis_data:/data
    network_mode: host
    expose:
      - 6379

  celeryworker:
    <<: *django
    image: todo_local_celeryworker
    container_name: todo_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    command: /start-celeryworker
    network_mode: host

  celerybeat:
    <<: *django
    image: todo_local_celerybeat
    container_name: todo_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    command: /start-celerybeat
    network_mode: host

  flower:
    <<: *django
    image: todo_local_flower
    container_name: todo_local_flower
    expose:
      - 5555
    command: /start-flower
    network_mode: host

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: todo_local_keycloak
    env_file:
      - ./.envs/.local/.keycloak
    command: start-dev --import-realm
    expose:
      - 8080
    volumes:
      - ./compose/local/keycloak/realm-export:/opt/keycloak/data/import
    network_mode: host
