volumes:
  todo_local_postgres_data: {}
  todo_local_postgres_data_backups: {}
  todo_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: todo_local_django
    container_name: todo_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
      - keycloak
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: todo_production_postgres
    container_name: todo_local_postgres
    volumes:
      - todo_local_postgres_data:/var/lib/postgresql/data
      - todo_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: todo_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: todo_local_redis
    volumes:
      - todo_local_redis_data:/data

  celeryworker:
    <<: *django
    image: todo_local_celeryworker
    container_name: todo_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: todo_local_celerybeat
    container_name: todo_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: todo_local_flower
    container_name: todo_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: todo_local_keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    command: start-dev --import-realm
    ports:
      - '8080:8080'
    volumes:
      - ./compose/local/keycloak/realm-export:/opt/keycloak/data/import
