# Generated by Django 5.1.12 on 2025-09-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sub', models.CharField(help_text='Keycloak user subject (sub claim from JWT)', max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_sub'], name='todos_todo_user_su_c4ecfd_idx'), models.Index(fields=['completed'], name='todos_todo_complet_334461_idx')],
            },
        ),
    ]
