# Generated by Django 5.1.12 on 2025-10-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keycloak_id',
            field=models.CharField(blank=True, help_text='Keycloak user ID (sub)', max_length=255, null=True, unique=True, verbose_name='Keycloak User Id'),
        ),
    ]
